<?php
$servername = "localhost";
$username = "root";
$password = "";
//$password = "F&-25mUzU&xrSv[N";
$database = "college";
$conn = mysqli_connect($servername,$username,$password,$database);


if(!$conn){
    die("sorry we failed to connect: ". mysqli_connect_error());
}


if($_SERVER['REQUEST_METHOD']=='POST'){
    $fname = $_POST['firstname'];
    $mname = $_POST['middlename'];
    $lname = $_POST['lastname'];
    $fathername = $_POST['fathername'];
    $email = $_POST['email'];
    $contact = $_POST['contact'];
    $pincode = $_POST['pincode'];
    $crn = $_POST['cr'];
    $en = $_POST['en'];
    //$rn = $_POST['rn'];
    $dep = $_POST['department'];
    $course = $_POST['course'];
    $cer1 = $_POST['certificate1'];
    $cer2= $_POST['certificate2'];
    $cer3 = $_POST['certificate3'];
    $ch1 = implode($cer1);
    $ch2 = implode($cer2);
    $ch3 = implode($cer3);
    //echo $ch1 ,$ch2 , $ch3;
}

$sqlcheck = "SELECT * FROM `collegetable2` WHERE RollNo= '$crn' ";
$resultcheck = mysqli_query($conn, $sqlcheck);
$rowcheck= mysqli_num_rows($resultcheck);

if($rowcheck>=1){
    $sql = "UPDATE `collegetable2` SET `TransferCertificate`='$ch1',`marksheet`='$ch2',`AchievmentCertificate`='$ch3' WHERE RollNo = '$crn' ";
}else{
    $sql = "INSERT INTO `collegetable2`(`FirstName`, `MiddleName`, `LastName`, `FatherName`, `email`, `ContactNumber`, `pincode`, `EnrollmentNo`, `RollNo`, `department`, `course`, `TransferCertificate`, `marksheet`, `AchievmentCertificate`) VALUES ('$fname','$mname','$lname','$fathername','$email','$contact','$pincode','$en','$crn','$dep','$course','$ch1','$ch2','$ch3')";
}
$result = mysqli_query($conn, $sql);
if($result){

    //echo "the record has been submited successfully <br> very soon you will be notified for same";

    //mail  
    $to = "mansisaxena670@gmail.com";
    $to2 = "$email";
    $subject = "mail for certificate widthrawing";
    $subject2 = "mail from college";
    $name = $fname . " ".$lname;
    $message = "you will be informed via email for further updates.";
    $message2 = "This is an autogenerated email please donot reply to it.";

    $txt =" Name = ". $name . "\r\n father's Name = " . $fathername . "\r\n email = " . $email . "\r\n contact = " . $contact . "\r\n College Rollno. = " . $crn . "\r\n Enrollment no. = " . $en . "\r\n Department = " . $dep . "\r\n course. = " . $course . "\r\n Applied for Certificates. = " . $checkbox  ;

    $txt2 =" Name = ". $name ."\r\n FatherName = " . $fathername ."\r\n contact = " . $contact ."\r\n Email = " . $email ."\r\n Enrollment No = " . $en ."\r\n College Rollno. = " . $crn ."\r\n course = " . $course ."\r\n department = " . $dep ."\r\n applied for certificate = " . $checkbox  . "\r\n " .  $message  . "\r\n " . $message2;
    $headers2 = "From: bhaskar acharya college of applied science";
    $headers = "$email";


    if($email!=NULL){
        mail($to,$subject,$txt,$headers);
        mail($to2,$subject2,$txt2,$headers2);
    }else{
        //echo "not send";
    }
    header("location:thanks.html");
}
    //
else{
    //echo mysqli_error($conn);
    header("Location:regret.html");
}
?> 